export const CAREER_SKILLS = [
  'Act as Liaison',
  'Adapt to Change',
  'Analyze',
  'Budget',
  'Classify',
  'Computer Literate',
  'Conceptualize',
  'Counsel',
  'Customer Service',
  'Deal with Ambiguity',
  'Deal with Feelings',
  'Delegate',
  'Design',
  'Entertain/Perform',
  'Estimate',
  'Evaluate',
  'Expedite',
  'Implement',
  'Improvise',
  'Initiate Change',
  'Innovate/Invent',
  'Interview for Information',
  'Maintain Records',
  'Make Arrangements',
  'Make Decisions',
  'Mediate',
  'Mentor',
  'Monitor',
  'Motivate',
  'Negotiate',
  'Observe',
  'Perceive Intuitively',
  'Portray Images',
  'Proofread, Edit',
  'Read for Information',
  'Research Online',
  'Sell',
  'Strategize',
  'Supervise',
  'Synthesize',
  'Team Work',
  'Teach, Train',
  'Test',
  'Visualize',
  'Work with Numbers',
  'Write',
] as const;

export type CareerSkill = (typeof CAREER_SKILLS)[number];
