export const CAREER_VALUES = [
  'Advancement',
  'Adventure',
  'Aesthetics',
  'Affiliation',
  'Artistic Creativity',
  'Change and Variety',
  'Challenging Problems',
  'Community',
  'Competition',
  'Creative Expression',
  'Creativity',
  'Diversity',
  'Environment',
  'Exercise Competence',
  'Excitement',
  'Family',
  'Fast Pace',
  'Friendships',
  'Fun and Humor',
  'Group & Team',
  'Help Others',
  'Help Society',
  'High Earnings Anticipated',
  'Honesty and Integrity',
  'Independence',
  'Influence People',
  'Intellectual Status',
  'Job Tranquility',
  'Knowledge',
  'Location',
  'Make Decisions',
  'Moral Fulfillment',
  'Personal Safety',
  'Physical Challenge',
  'Power and Authority',
  'Practicality',
  'Precision Work',
  'Profit, Gain',
  'Public Contact',
  'Recognition',
  'Security',
  'Spirituality',
  'Stability',
  'Status',
  'Steep Learning Curve',
  'Structure and Predictability',
  'Supervision',
  'Time Freedom',
  'Tradition',
  'Work Alone',
  'Work on the Frontiers of Knowledge',
  'Work Under Pressure',
  'Work with Others',
  'Work-Life Balance',
] as const;

export type CareerValue = (typeof CAREER_VALUES)[number];
