export const CAREER_SKILLS = [
  'Analyze',
  'Portray Images',
  'Write',
  'Make Decisions',
  'Research Online',
  'Visualize',
  'Expedite',
  'Negotiate',
  'Sell',
  'Estimate',
  'Budget',
  'Computer Literate',
  'Monitor',
  'Design',
  'Innovate/Invent',
  'Interview for Information',
  'Make Arrangements',
  'Entertain/Perform',
  'Proofread, Edit',
  'Perceive Intuitively',
  'Conceptualize',
  'Synthesize',
  'Evaluate',
  'Teach, Train',
  'Deal with Ambiguity',
  'Maintain Records',
  'Improvise',
  'Counsel',
  'Implement',
  'Delegate',
  'Customer Service',
  'Adapt to Change',
  'Initiate Change',
  'Strategize',
  'Team Work',
  'Observe',
  'Motivate',
  'Act as Liaison',
  'Read for Information',
  'Classify',
  'Supervise',
  'Test',
  'Deal with Feelings',
  'Mediate',
  'Work with Numbers',
  'Mentor',
] as const;

export type CareerSkill = (typeof CAREER_SKILLS)[number];
