export const CAREER_VALUES = [
  'Creative Expression',
  'Affiliation',
  'Job Tranquility',
  'Work Alone',
  'Challenging Problems',
  'Competition',
  'Time Freedom',
  'Security',
  'Advancement',
  'Artistic Creativity',
  'Adventure',
  'Tradition',
  'Supervision',
  'Community',
  'Profit, Gain',
  'Work-Life Balance',
  'Group & Team',
  'Status',
  'Family',
  'Structure and Predictability',
  'Fast Pace',
  'Intellectual Status',
  'Public Contact',
  'Help Society',
  'Fun and Humor',
  'Change and Variety',
  'Precision Work',
  'Personal Safety',
  'Creativity',
  'Work on the Frontiers of Knowledge',
  'Aesthetics',
  'Recognition',
  'Knowledge',
  'Exercise Competence',
  'Steep Learning Curve',
  'Power and Authority',
  'Independence',
  'Work with Others',
  'Honesty and Integrity',
  'Location',
  'Moral Fulfillment',
  'Spirituality',
  'Help Others',
  'Practicality',
  'Friendships',
  'Physical Challenge',
  'High Earnings Anticipated',
  'Excitement',
  'Environment',
  'Work Under Pressure',
  'Make Decisions',
  'Stability',
  'Influence People',
  'Diversity',
] as const;

export type CareerValue = (typeof CAREER_VALUES)[number];
