export const CAREER_STRENGTHS = [
  'Achiever',
  'Activator',
  'Adaptability',
  'Analytical',
  'Arranger',
  'Belief',
  'Command',
  'Communication',
  'Competition',
  'Connectedness',
  'Consistency',
  'Context',
  'Deliberative',
  'Developer',
  'Discipline',
  'Empathy',
  'Focus',
  'Futuristic',
  'Harmony',
  'Ideation',
  'Includer',
  'Individualization',
  'Input',
  'Intellection',
  'Learner',
  'Maximizer',
  'Positivity',
  'Relator',
  'Responsibility',
  'Restorative',
  'Self-Assurance',
  'Significance',
  'Strategic',
  'Woo',
] as const;

export type CareerStrength = (typeof CAREER_STRENGTHS)[number];
